### ISSUE TITLE
功能添加提问

### ISSUE THREAD

**Issue by poify** [babalae/genshin-account#14]
我的PC里有国服和国际服2个客户端，我想A账号是打开国服客户端，B账号打开国际服客户端。这个功能添加吗？

**Comment by huiyadanli** [comment]
国服A账号登录后，国际服保存的B账号会失效不？、

我这边没有国际服客户端没法判断两者保存账号信息的位置是否一致

**Comment by poify** [comment]
> Member

不会，A账号无论是登录还是退出，B账号都不会失效。2个客户端的账号互不干预

**Comment by huiyadanli** [comment]
那这个功能好像没啥必要。。。只要直接快捷方式启动就行了，没有切换账号的需求。。。
