### ISSUE TITLE
不明bug

### ISSUE THREAD

**Issue by av332** [babalae/genshin-account#15]
![bug](https://user-images.githubusercontent.com/39397602/180618093-a68fa834-4416-48d1-a719-94465ab4066f.png)
同平日一样启动程序，就报bug了，重启/管理员运行仍存在错误
还好UserData里面的文件还正常，重新下载程序把文件夹拉过去就可以正常使用了
本机配置 i7-4770k, gtx660, 16gb ram, plextor px-512m6s
win10 教育版 21H2
bug report见下，希望能帮到您，谢谢大大
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Configuration.ConfigurationErrorsException: 配置系统未能初始化 ---> System.Configuration.ConfigurationErrorsException: “.”(十六进制值 0x00)是无效的字符。 第 9 行，位置 1。 (C:\Users\LAU\AppData\Local\GenshinAccount\GenshinAccount.exe_Url_qmvbi0fb1jmrm2f1a5hfaz4ktkjukanm\1.5.0.0\user.config line 9) ---> System.Xml.XmlException: “.”(十六进制值 0x00)是无效的字符。 第 9 行，位置 1。
   在 System.Xml.XmlTextReaderImpl.Throw(Exception e)
   在 System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   在 System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   在 System.Xml.XmlTextReaderImpl.ParseText()
   在 System.Xml.XmlTextReaderImpl.ParseElementContent()
   在 System.Xml.XmlTextReaderImpl.Read()
   在 System.Xml.XmlTextReader.Read()
   在 System.Configuration.XmlUtil.StrictReadToNextElement(ExceptionAction action)
   在 System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   在 System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   在 System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   在 System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   在 System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   在 System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   在 System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   在 System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   在 System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   在 System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   在 System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   在 System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   在 System.Configuration.ConfigurationManager.GetSection(String sectionName)
   在 System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   在 System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   在 System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   在 System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   在 System.Configuration.SettingsBase.get_Item(String propertyName)
   在 System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   在 System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   在 GenshinAccount.Properties.Settings.get_AutoRestartYSEnabled()
   在 GenshinAccount.FormMain.FormMain_Load(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4515.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
GenshinAccount
    程序集版本:1.5.0.0
    Win32 版本:1.5.0.0
    基本代码:file:///C:/Users/LAU/Desktop/GenshinAccount.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4515.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4488.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4390.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4515.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Management
    程序集版本:4.0.0.0
    Win32 版本:4.8.4435.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.xml.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Xml.resources.dll
----------------------------------------
System.Configuration.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.resources/v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a/System.Configuration.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by av332** [comment]
把程序和UserData直接放到桌面会产生该bug.

**Comment by huiyadanli** [comment]
这个报错的原因是因为软件保存的配置中出现了无法解析的特殊字符。。。

移动软件位置会重新生成配置。

直接解决最简单的方案就是把对应报错路径的配置文件删掉。

`C:\Users\LAU\AppData\Local\GenshinAccount\GenshinAccount.exe_Url_qmvbi0fb1jmrm2f1a5hfaz4ktkjukanm\1.5.0.0\user.config`

**Comment by av332** [comment]
问题已解决，谢谢~

**Comment by av332** [comment]
> 这个报错的原因是因为软件保存的配置中出现了无法解析的特殊字符。。。
> 
> 移动软件位置会重新生成配置。
> 
> 直接解决最简单的方案就是把对应报错路径的配置文件删掉。
> 
> `C:\Users\LAU\AppData\Local\GenshinAccount\GenshinAccount.exe_Url_qmvbi0fb1jmrm2f1a5hfaz4ktkjukanm\1.5.0.0\user.config`

问题已解决，谢谢~
