### ISSUE TITLE
能否增加pc云原神账号切换功能

### ISSUE THREAD

**Issue by real-LEONEAST** [babalae/genshin-account#19]
pc云原神账号切换同样很麻烦，尝试了下直接把路径设置到云原神路径，但提示目录没有原神。

**Comment by real-LEONEAST** [comment]
https://www.bilibili.com/read/cv11004659#reply159319689824
这个办法好像能实现，不过能集成一下吗

**Comment by huiyadanli** [comment]
https://github.com/babalae/mihoyo-starter 支持了，整了个全新的项目

账户信息在这里：
`HKEY_CURRENT_USER\Software\miHoYo\云·原神` 下的 `MIHOYOSDK_ADL_0`

![image](https://user-images.githubusercontent.com/15783049/235349774-8b4660d6-c316-44bc-8ef7-1a3ffd215d9d.png)
