### ISSUE TITLE
界面能否优化下，账号排列的好小啊。。最好双击就能直接切换 是否可以又这种功能

### ISSUE THREAD

**Issue by Youhe0309** [babalae/genshin-account#2]
很棒的工具

**Comment by huiyadanli** [comment]
[1.3](https://github.com/babalae/genshin-account/releases/tag/v1.3)  已经添加以下功能

  * 添加 [切换时自动重启原神] 、 [切换时不弹出提示] 选项，切换更加方便
  * 双击账号列表可以直接切换
  * 放大了账号列表
