### ISSUE TITLE
不能跨设备替换账号吗？

### ISSUE THREAD

**Issue by TuDouqwq** [babalae/genshin-account#21]

**Comment by huiyadanli** [comment]
原神早期版本可以跨设备，现在不行。

你是想要盗号吗？

**Comment by TuDouqwq** [comment]
这个咋盗号，我想做个云端备份




窃星
***@***.***







                       
原始邮件
                       
                     

发件人："辉鸭蛋"< ***@***.*** &gt;;

发件时间：2023/10/30 9:53

收件人："babalae/genshin-account"< ***@***.*** &gt;;

抄送人："TuDouqwq"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [babalae/genshin-account] 不能跨设备替换账号吗？ (Issue #21)




 
原神早期版本可以跨设备，现在不行。
 
你是想要盗号吗？
