### ISSUE TITLE
出现失效

### ISSUE THREAD

**Issue by maybe1026** [babalae/genshin-account#7]
有时账号切换会失效清空

**Comment by huiyadanli** [comment]
是不是某个账号太久没登录了

**Comment by maybe1026** [comment]
仅仅过了半天就失效了，已经三次了，以前都正常的

**Comment by huiyadanli** [comment]
是扫码登录的吗

**Comment by maybe1026** [comment]
好像都不行，我再观察观察

**Comment by maybe1026** [comment]
现在好了。我不久之前中过蠕虫病毒，这个exe被种过病毒，用火绒把exe整好了，好像就是这个时候出现的失效。我重新下载了一下，现在一切正常。不知道是不是病毒的问题。

**Comment by huiyadanli** [comment]
应该不是，蠕虫病毒不会影响软件本身的功能。。
